---
abstract: 'Fast and extensible JSON-RPC Service Framework (CGI/mod_perl/Nginx)'
author:
  - 'Olli Hollmen'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JRPC
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 0
  Data::Dumper: 0
  HTTP::Server::Simple: 0
  JSON::XS: 0
  LWP: 0
version: 0.61
